# Generated by Django 5.0.4 on 2024-04-21 11:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="link",
            name="link_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
